services:
  - type: worker    # use worker for Telegram bots
    name: bot
    env: python
    plan: free
    buildCommand: |
      apt-get update && apt-get install -y \
        tesseract-ocr \
        tesseract-ocr-amh \
        libtesseract-dev \
        libleptonica-dev
      pip install -r requirements.txt
    startCommand: python bot.py
